### ISSUE TITLE
Making it Responsive?

### ISSUE THREAD

**Issue by scazzy** [ericleong/zoomwall.js#2]

**Comment by ericleong** [comment]
If you want bigger images on smaller screens, you can adjust the height of each row with media queries.

```css
@media (max-width: 640px) {
	.zoomwall img {
		height: 20vw;
	}
}
```

If you want images to have the same height, regardless of screen size, you could do something like 

```css
.zoomwall img {
	height: 200px;
}
```

On smaller screens, fewer images would fit on each row.

I haven't figured out the best number for every case, so I think it's better if you just override the default (`15vw`) in your own CSS.
