### ISSUE TITLE
Single image doesn't work as expected

### ISSUE THREAD

**Issue by JLMorales** [ericleong/zoomwall.js#3]
it wont scale as it would when there are two or more, and it also does not zoom in on it if it is the only image in the container.

**Comment by JLMorales** [comment]
Kept at it and found out that it zooms in on a single image only if a specific height is applied to the container.

**Comment by ericleong** [comment]
This is a tough one because of how the animation works and the relationship between the image's aspect ratio and the viewport aspect ratio. But a quick fix would be to apply a style that makes the container fixed when in lightbox mode:

```css
.zoomwall.lightbox {
    position: fixed;
    width: 100vw;
    min-height: 100vh;
    top: 0;
}
```

It's a bit dirty though, because it causes the page to reflow and you lose your scroll position. I think a good solution would depend a lot on your layout.
